# Generated by Django 6.1 on 2026-09-08 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1024)),
                ('event_types', models.JSONField()),
                ('encrypted_secret', models.TextField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_version', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=96)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_status_code', models.PositiveSmallIntegerField(null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=32)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='webhooks.webhookdelivery')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('delivery', 'number'), name='webhook_attempt_number_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='webhooks_we_status_afd94b_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event_id'), name='webhook_endpoint_event_unique'),
        ),
    ]
