# Generated by Django 6.1 on 2026-09-06 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=96)),
                ('actor_id', models.UUIDField(null=True)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('outcome', models.CharField(default='success', max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_id', 'created_at'], name='audit_target_created_idx')],
            },
        ),
    ]
