# Generated by Django 6.1 on 2026-09-08 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0002_apikey_family_id'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=96)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='projects.apiservice')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='APIKeyPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='credentials.apikey')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='access.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment_kind', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], editable=False, max_length=4)),
                ('key_family_id', models.UUIDField(editable=False, null=True)),
                ('name', models.CharField(max_length=128)),
                ('algorithm', models.CharField(choices=[('fixed_window', 'fixed_window'), ('token_bucket', 'token_bucket'), ('daily', 'daily'), ('monthly', 'monthly')], editable=False, max_length=16)),
                ('dimension', models.CharField(choices=[('shared', 'Shared'), ('key', 'Key family')], editable=False, max_length=8)),
                ('config', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('service', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.apiservice')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PolicyRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='access.policy')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_id', models.UUIDField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('used', models.PositiveBigIntegerField(default=0)),
                ('adjustment', models.BigIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.policy')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.BigIntegerField()),
                ('reason', models.CharField(max_length=256)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.quotabucket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='permission_service_name'),
        ),
        migrations.AddConstraint(
            model_name='apikeypermission',
            constraint=models.UniqueConstraint(fields=('key', 'permission'), name='key_permission_unique'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['organization', 'environment_kind', 'is_active'], name='access_poli_organiz_dd7bce_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('environment_kind__in', ('test', 'live'))), name='policy_valid_environment'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__in', ('shared', 'key'))), name='policy_valid_dimension'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('key_family_id__isnull', True), ('service__isnull', False), _connector='OR'), name='key_policy_has_service'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('service__isnull', True), ('project__isnull', False), _connector='OR'), name='service_policy_has_project'),
        ),
        migrations.AddConstraint(
            model_name='policyrevision',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='policy_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotabucket',
            constraint=models.UniqueConstraint(fields=('policy', 'dimension_id', 'period_start'), name='quota_bucket_unique'),
        ),
    ]
