# Generated by Django 6.1 on 2026-09-08 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold', models.PositiveSmallIntegerField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.quotabucket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bucket', 'threshold'), name='quota_notice_unique')],
            },
        ),
    ]
