# Generated by Django 6.1 on 2026-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtokensession',
            name='credential_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
