# Generated by Django 6.1 on 2026-09-08 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_id', models.UUIDField(null=True)),
                ('family_id', models.UUIDField(null=True)),
                ('method', models.CharField(max_length=7)),
                ('outcome', models.CharField(max_length=32)),
                ('units', models.PositiveBigIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('decision', models.JSONField()),
                ('status_code', models.PositiveSmallIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.apiservice')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QuotaReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units', models.PositiveBigIntegerField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.quotabucket')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='usage.usageevent')),
            ],
        ),
        migrations.CreateModel(
            name='AggregationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aggregation_receipt', to='usage.usageevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.DateTimeField()),
                ('key_id', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000'))),
                ('method', models.CharField(max_length=7)),
                ('outcome', models.CharField(max_length=32)),
                ('requests', models.PositiveBigIntegerField(default=0)),
                ('units', models.PositiveBigIntegerField(default=0)),
                ('latency_ms_total', models.PositiveBigIntegerField(default=0)),
                ('latency_ms_max', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.apiservice')),
            ],
            options={
                'ordering': ('-hour', '-id'),
                'constraints': [models.UniqueConstraint(fields=('service', 'hour', 'key_id', 'method', 'outcome'), name='usage_aggregate_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['service', 'created_at'], name='usage_usage_service_8ef2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['key_id', 'created_at'], name='usage_usage_key_id_7cb9c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotareservation',
            constraint=models.UniqueConstraint(fields=('event', 'bucket'), name='quota_event_bucket_unique'),
        ),
    ]
