# Generated by Django 6.1 on 2026-09-08 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('filters', models.JSONField()),
                ('status', models.CharField(default='queued', max_length=12)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
    ]
