# Generated by Django 6.1 on 2026-09-08 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_id', models.UUIDField()),
                ('scope', models.CharField(max_length=160)),
                ('key_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('resource_id', models.UUIDField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'scope', 'key_hash'), name='core_command_idempotency_unique')],
            },
        ),
    ]
