# Generated by Django 6.1 on 2026-09-08 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64)),
                ('archived_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], editable=False, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='projects.project')),
            ],
            options={
                'ordering': ('kind',),
            },
        ),
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64)),
                ('audience', models.CharField(editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='projects.environment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('environment', 'slug'), name='service_environment_slug_unique'), models.UniqueConstraint(fields=('environment', 'audience'), name='service_environment_audience_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='project_org_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('project', 'kind'), name='project_environment_unique'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('test', 'live'))), name='environment_canonical_kind'),
        ),
    ]
