# Generated by Django 6.1 on 2026-09-08 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('verifier', models.CharField(editable=False, max_length=64)),
                ('pepper_version', models.CharField(editable=False, max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='integration_credentials', to='projects.apiservice')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('consumer_reference', models.CharField(blank=True, max_length=128)),
                ('verifier', models.CharField(editable=False, max_length=64)),
                ('pepper_version', models.CharField(editable=False, max_length=16)),
                ('display_prefix', models.CharField(editable=False, max_length=32)),
                ('last_four', models.CharField(editable=False, max_length=4)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=32)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='projects.apiservice')),
                ('successor', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predecessor', to='credentials.apikey')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['service', 'revoked_at', 'expires_at'], name='credentials_service_44afa2_idx'), models.Index(fields=['service', 'last_used_at'], name='credentials_service_93e7a9_idx')],
            },
        ),
    ]
